import "./globals.css"
import { BethanyElingston } from "./utils/custom-font"
import { Manrope } from "next/font/google"


export const metadata = {
  title: "Schools of tomorrow",
  description: "Generated by create next app",
}

const ManRope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin']
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${BethanyElingston.variable} ${ManRope.variable} bg-main overflow-hidden flex flex-col items-center justify-center`}
      >
        {children}
      </body>
    </html>
  );
}
